### ISSUE TITLE
Some questions about building nalu-wind

### ISSUE THREAD

**Issue by Z0907Q** [Exawind/nalu-wind#1249]
Dear scientist:
When I was building nalu-wind, I ran into some problems that were never solved.The Trilinos problem, for example, has never been solved.Trilinos never succeeded when building with spack.I would like to ask you to take some time to solve this problem and look forward to receiving your reply.

**Comment by psakievich** [comment]
Please stop opening redundant issues on multiple repositories. This is redundant to #1247, and you have not responded since my last suggestion. I am going to close this one and the others you have opened.  This software is opensource and free to use, but the support is mainly targeted to US -DOE laboratories and other customers funding this work. Please remember you are not paying for this and our help to you is courtesy.
