### ISSUE TITLE
Wall distance equation can't converge when no wall BCs present (overset)

### ISSUE THREAD

**Issue by ndevelder** [Exawind/nalu-wind#1262]
Hi All,

I've got a nalu-nalu exawind-driver overset case where the turbine is in the middle of the domain and all the background domain side BCs are symmetry. Nalu-wind fails and it appears to be related to the wall distance equation not converging? If I change one domain BC to a wall BC, everything seems ok. 

This is a total edge case, but just documenting here for future. Maybe we need a new flag to be able to turn on/off treating symmetry BCs like walls for wall distance equation? Or the overset boundary needs to communicate it's own wall distance but that maybe gets slow with moving meshes and needing to re-solve.

**Comment by psakievich** [comment]
Hmm interesting case. Yes we should figure this out. Seems like it should be able to converge if we supply the wall distance to the overset boundary as long as we solve the section with no walls last. Presumably we don't really need wall distance for these boxes since they should be far enough from a wall to need the term in the turbulence equations though.

**Comment by ndevelder** [comment]
I'm going to close this for now so as not to clutter the issue list...I don't believe this is important enough for anyone at the moment, and for the type of cases it affects, there is a workaround. Feel free to re-open as needed.
