### ISSUE TITLE
Parmetis as an automatic decomposition type

### ISSUE THREAD

**Issue by itopcuoglu** [Exawind/nalu-wind#1294]
Currently, we have to use the stk_balance.exe executable on exodus files to partition meshes using parmetis. Using the automatic decomposition option RCB requires the `stk_rebalance: parmetis` option  to avoid inadequate partitioning configurations such as the one described in this paper in figure 4.

https://dl.acm.org/doi/10.1145/3458817.3476185

It could be beneficial to add parmetis as a direct automatic decomposition option.

**Comment by psakievich** [comment]
This can sort of be done already. See here: https://github.com/Exawind/exawind-cases/blob/2600d59fced07d9d3798eef8ba26fb87fe4b7b21/16_turb_abl_fsi/template_files/nrel5mw_nalu.yaml#L75-L77

``` yaml
  automatic_decomposition_type: rcb
  rebalance_mesh: yes
  stk_rebalance_method: parmetis
```

Stk doesn't support it as a automatic decomp type, but you can use it through rebalance. This is exactly what stk balance does. I believe parmetis works off an initial decomposition type so the initial decomp type is rcb or rib with stk_balance and then it applies parmetis

**Comment by tasmith4** [comment]
@itopcuoglu, I've spent time working on stk_balance in the past, and the short version is: under the hood in stk_balance the automatic decomposition is handled in a completely different place than the parmetis decomp.  Unfortunately, changing stk_balance to add parmetis as an auto-decomp may not even be possible, and if it is, would require such massive changes to existing stk code that it's almost certainly unrealistic.

I'm going to go ahead and close this issue, because unfortunately I think @psakievich's solution is the best one available, so I don't think there's anything for us to do on the Nalu-Wind development side.  Please do feel free to continue the conversation here or find me on slack if you'd like more detail on this.
