### ISSUE TITLE
Realm::set_hypre_global_id() is not included in any timer.

### ISSUE THREAD

**Issue by DrBooom** [Exawind/nalu-wind#208]
It appears that the MPI_Allgather inside Realm::set_hypre_global_id() is not included in any of the timers. Since the Tpetra stack does this same operation (scan_sum) inside it's equation system "Init" timer, it seems that this hypre function should be included somewhere so that comparisons include all work and mpi communication.

**Comment by sayerhs** [comment]
@DrBooom That is a good point, the time spent needs to be captured somewhere other than the overall runtime. However, in case of `set_hypre_global_id` it is done once per timestep regardless of how many equation systems there are, so we can't just add this time to all the equation systems `init` because we don't perform this separately for momentum, continuity, enthalpy, turbulence equation systems, whereas (if I understood you correctly) `scan_sum` is executed separately for each instance of `TpetraLinearSystem`. I am wondering how we should go about comparing these times in this case.

**Comment by DrBooom** [comment]
The obvious answer is to create the local and sharedNotOwned Tpetra maps once, and re-use them for each subsequent equation system. It would both improve performance, and allow direct comparison.
