### ISSUE TITLE
Tpetra Segregated System

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#249]
This issue is here to keep track of progress made to implement a segregated linear system with the Tpetra stack in nail-wind.
There is already a working implementation in my fork but rebasing on head and merging afterwards seems quite hard due to many changes in `nalu-wind`.
I will take an incremental approach in which I slowly introduce all the features I need to get to the full segregated linear system. This should make it easy to review my PRs.

1. [x] Switch from `LinSys::Vector` to `LinSys::MultiVector` in `LinearSolver`, `LinearSystem` and `TpetraLinearSystem` classes. (done through PR #251 )
2. [x] Create a new type of linear system: `TpetraSegregatedLinearSystem` this will initially be implemented as a copy of the `TpetraLinearSystem` class (done in PR #258 and #260)
3. [x] Actually implement and interface the specific methods for a segregated system.

**Comment by alanw0** [comment]
Do we really need a new linear system class? That sounds like a lot of code duplication. I don't know how specifically your work is implemented, but I was hoping it would make the momentum equation more similar to the scalar equations. Adding a new linear system class sounds like it would be very different. I'll be interested to hear/see more details.

**Comment by sayerhs** [comment]
@alanw0 While don't need an entirely new class, you'll want to override `sumInto` class so that even though the algorithms are `3x3` we are just populating a scalar matrix. In `HypreLinearSystem` vs. `HypreUVWLinearSystem` the differences are in the logic of handling `numDof_`, `sumInto` and the `loadComplete` steps.

**Comment by alanw0** [comment]
@sayerhs does sumInto need to only keep the 0,0 position of each 3x3 and discard the rest, or does it need to do something fancier than that? If it is just discarding most of the coefficients, maybe we should pass an option to the relevant kernels so that they don't waste time calculating those coefficients.

**Comment by sayerhs** [comment]
@sayerhs In scalar/continuity kernels `lhs` is just `(1, 1)`. For momentum, the time derivative kernel should populate the diagonal `(i, i) i = 1..3` and not just `(0, 0)`. I'll have to look through the other kernels to make sure that they are not populate off-diagonal terms.

**Comment by lucbv** [comment]
@alanw0 @sayerhs I did not plan to touch anything but LinearSolver and LinearSystem, I did try to do something fancier initially but realized quickly that there are a lot of physic kernels that would need to be changed otherwise.
I do not mind implementing the segregated linear system as an option in the TpetraLinearSystem, I think that could be done without much extra work from me but it probably means overloading most of the methods in the class as `numDof_` needs to be substituted ignored in most of the class.

**Comment by sayerhs** [comment]
@alanw0 Sorry, I misunderstood your question. You are correct that it only requires `(0, 0)` for each node. I opted for subclassing HypreLinearSystem instead of modifying every algorithm and kernel because it requires adding this flag to every momentum NGP kernels edge/node/elem traditional algorithms. If someone wants to take on the effort of adding `if` conditions to all kernels,  that would be great but it will be an effort to support all different modes of operation.

**Comment by lucbv** [comment]
@sayerhs @alanw0 pretty much all the `AssembleXYZ` classes would need to have an `if` or an overload for the segregated case.

**Comment by alanw0** [comment]
@sayerhs @lucbv Do we want the segregated case to be an option, or do we want it to be the only way going forward? What are the pros and cons?

**Comment by sayerhs** [comment]
@alanw0 On the Hypre side, segregated/monolithic is an option that user can select at runtime. For preserving backwards compatibility, I would like to keep this as an option. Also for small problems, we might not see much runtime benefit of doing segregated and might as well get the extra accuracy of the monolithic solves. For really large problems, segregated offers good speed-up in init phase. I'll have to go check our old timings, but my memory is that the assemble cost (kernel processing) wasn't that different for momentum vs. continuity.

**Comment by alanw0** [comment]
@lucbv @sayerhs Shreyas and I spoke on the phone about this. I understand a little better now. We don't want to make the segregated approach turned on all the time, due to accuracy issues, it should just be an option for when a user wants to make the trade-off for improved speed. Putting conditional logic throughout the kernels also sounds bad. So adding a segregated linear system is probably the best option, but let's wait and do that after we pull the graph creation out of TpetraLinearSystem.
It would be good if we could first consolidate global-ids (use hypre-global-id for both tpetra and hypre, maybe rename it to linsys-global-id). I'll try to check in with Chris (@DrBooom ) and see if he's still doing anything on this front.
After that, pull graph creation out of TpetraLinearSystem so that a single graph can be used by various equation-systems.
Once that's done, TpetraLinearSystem will be much smaller and creating a segregated version of it should produce a lot less duplicated logic.
@lucbv what do you think of this? I can try to get these two pre-requisite tasks done fairly quickly.

**Comment by sayerhs** [comment]
Done in #265
