### ISSUE TITLE
nalu-wind build error:  'put_field_on_mesh' is not a member of 'stk::mesh'

### ISSUE THREAD

**Issue by Cfdbooks** [Exawind/nalu-wind#37]
I tried to build nalu-wind manually following the instruction and got the error:  'put_field_on_mesh' is not a member of 'stk::mesh'. The accompanied  required TPLs seem ok and I am using the latest master of Trilinos I think(git clone https://github.com/trilinos/Trilinos.git). 
![img_3106](https://user-images.githubusercontent.com/16715436/45629111-34641580-bac8-11e8-8bdd-25d77b88550f.JPG)

**Comment by sayerhs** [comment]
The latest commit of Trilinos was on Sept 11, 2019 (https://github.com/trilinos/Trilinos/commits/master). Can you please fetch this commit and compile nalu-wind against that? You'll need a commit that is newer than this: https://github.com/trilinos/Trilinos/commit/de635abc146449dc1c4dbbea65cefda91946755e

**Comment by alanw0** [comment]
This is due to a stk API change that is in the Trilinos develop branch but hasn't yet been promoted to the Trilinos master branch.
Periodically this will happen, as new development happens on the develop branch and then a window of time follows before the master branch 'catches up'. In nalu-wind we probably need to discuss a process for managing this window.

**Comment by Cfdbooks** [comment]
Now I am using both latest Trilinos and nalu-wind and have built the codes successfully. Thanks.
