### ISSUE TITLE
nvlink warnings from #379

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#382]
@overfelt Since the merge of #379 I am getting tons of nvlink warnings like the following, it is doing this for practically every NGP function that uses scratch views. I suspect this is because of the removal of `ifdef`s?

```
nvlink warning : Stack size for entry function '__nv_static_62__49_tmpxft_00006cda_00000000_6_TKEWallFuncAlg_cpp1_ii_8112f58a__ZN6Kokkos4Impl36cuda_parallel_launch_constant_memoryINS0_11ParallelForIZN6sierra4nalu8nalu_ngp18run_elem_algorithmIN3ngp10StaticMeshENS7_12FieldManagerENS4_16ElemDataRequestsEZNS4_14TKEWallFuncAlgINS4_15AlgTraitsEdgeGLILi2EEEE7executeEvEUlRNS5_12ElemSimdDataIS8_EEE_EEvRKNS5_8MeshInfoIT_T0_EEN3stk8topology6rank_tERKT1_RKNSP_4mesh8SelectorET2_EUlRKNS0_14CudaTeamMemberEE_NS_10TeamPolicyIJNS_4CudaENS_8ScheduleINS_7DynamicEEEEEES15_EEEEvv' cannot be statically determined
```

**Comment by overfelt** [comment]
Yes, this is unfortunate.  I talked to Dan Sunderland who works on Kokkos and he even brought this up with Nvidia but got no response.  Seems to be a relic of the time before relocatable device code, if everything is inlined it would be odd not to know the needed stack size.  Any virtual function call (i.e. master element call) will produce a warning like this since the stack size is undetermined.  I was getting a few of these before the change and I guess we can expect even more in the future

**Comment by sayerhs** [comment]
@overfelt What's weird is that if I remove your commit, I get a clean build without any warnings. So there is something about those specific methods that are causing stack size warnings.
