### ISSUE TITLE
STK SIMD broken on GPU build 

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#545]
[CDash](https://my.cdash.org/viewBuildError.php?buildid=1792601) indictates that STK SIMD doesn't work with nalu-wind GPU builds when using  trilinos/trilinos#39488e885

**Comment by alanw0** [comment]
jvo and dave have been working on converting nalu-wind to the new stk ngp stuff, they will do a gpu build with current trilinos to try to reproduce this. It's weird, because I thought the simd stuff was all appropriately guarded for cuda. In our sierra builds this isn't happening...
Anyway, we'll get it figured out right away.

**Comment by jvo1012** [comment]
@sayerhs, I was able to build nalu-wind with the latest version of Trilinos without any issues on ascicgpu22.  This was using gcc7.2.0 and nvcc10.1.243.  Do SNL developers have access to eagle?  I can also try building on summit if you know that the build is broken there too.

**Comment by sayerhs** [comment]
@jvo1012 So we were using CUDA 9.2.x on Eagle, Summit is also configured to use CUDA 9.2.x. I'll move to CUDA 10 and test, but if you can test it on Summit that would be great.

**Comment by jvo1012** [comment]
We decided to revert our changes to stk_simd in Trilinos as a temporary fix for nalu-wind.  We will push it again once we have everything working.

**Comment by sayerhs** [comment]
Thanks @jvo1012

**Comment by tasmith4** [comment]
We've been able to reproduce this error when the `-march=skylake -mtune=skylake` flags are specified during a CUDA build.  Based on the [exawind-builder setup for eagle](https://github.com/sayerhs/exawind-builder/blob/d80d124215eb62304671677059e0f679c1493710/envs/eagle.bash#L55), which specifically excludes these flags for CUDA builds, I suspect these flags do not play nicely with CUDA.

@jrood-nrel, is it possible to modify the automated build and test packages so that these flags are not added for CUDA builds of Trilinos and Nalu-Wind?

**Comment by tasmith4** [comment]
@sayerhs @jrood-nrel we've found a portable way to edit the Kokkos-SIMD header to keep this from happening, and will have these fixes in place the next time we enable Kokkos-SIMD for Trilinos.

So it's really up to you guys about the skylake flags -- if you feel they are inappropriate you can still take them out, but stk_simd should work regardless now.
