### ISSUE TITLE
refine and unrefine fraction in adapt.yaml

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#564]
Hi Nalu-wind team,

When using the mesh refinement function in nalu-preprocessing, the adapt*.yaml files are generated to be used as inputs in percept/mesh adapt.yaml.  Could anybody tell how the refine and unrefine fractions are designed? I can understand the definition of the fractions from percept manual (Sandia website). But I am curious if these fractions are a function of the box-sizes that we define for refinement layers? It seems they are hard-coded in NestedRefinement.cpp

I see the refine and unrefine fractions from NestedRefinement.cpp to be 0.9*(I+1)/num_levels, and 0.75*(I+1)/num_levels, with I = 0 to num_levels-1. However, I am interested to know how these numbers 0.9 and 0.75 were chosen. Any help?

-Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 They were arrived at through some numerical experimentation to match the box refinement that was desired as a function of the number of nested boxes. Feel free choose a different fraction if it suits your purposes.

**Comment by tchatte3** [comment]
@sayerhs Thanks for the reply. However, as per my understanding, the refine and unrefine functions should have no influence on the refined mesh size obtained after refining the coarse mesh right? 
These fractions are merely markers to refinement. Is there a way to control what the refined mesh size would be after one layer of refinement?

**Comment by sayerhs** [comment]
To elaborate further, the fractions are not functions of the box sizes, just the level of nesting. We want to create a refinement field that varies from `[0, 1]` that can be used to perform multiple passes (for each level of nested refinement) with percept. The idea then was if I just want to populate the field once, how can I pick out ranges so that at each level it will refine a desired region. After running preproces, you can examine the exodus output from `wind-utils` in ParaView and you'll see the refinement field varies around the edges of the boxes you specify. In that sense it will span the box-size but remains constant within that box. 

You'll have to consult the Percept manual to check on the size control. The current setup is using uniform refinement, i.e., at each call it will divide a HEX cell into 8 smaller (but equal sized) HEX cells. If you want an aggressive factor of 4 etc. you'll have to look in Percept manual for that.

**Comment by tchatte3** [comment]
@sayerhs Thanks a lot for such detailed explanation. It is much clear now (the refine and unrefine functions). I will look into the percept manual to check on controlling the cell-size refinement. 

This is really helpful.
