### ISSUE TITLE
Failing tests due to changes in NGP algorithm pathway

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#571]
The gold tests (GCC 4.9.4) have been [failing](https://my.cdash.org/buildSummary.php?buildid=1809756) for the past few days with diffs since ff9ee4fb (Trilinos/trilinos@1a965b8505). The tests were passing with 68c338d3 (Trilinos/trilinos@550334d445). Seems like @overfelt 's fix switching to NGP versions of the nodal gradient computation 8debd31742b11 is the most likely cause.

@alanw0 @overfelt can you confirm? If that is the case, we should determine if this is expected behavior and rebless the files, or if it requires more debugging.

**Comment by sayerhs** [comment]
@overfelt Have you had a chance to see if we can rebless these gold files?

**Comment by overfelt** [comment]
Shreyas,

Forgot to mention this at our meeting.

I looked at the failing tests for gcc 4.9.  Unfortunately I could not get 4.9 to build, I normally build gcc 7.4 so was not sure how to re-generate the gold files.
Also, since Linux gcc 4.9 and Linux gcc 7.4 produce different results, won't fixing 4.9 break 7.4?  From what I can see in the CMakeLists.txt, the tolerance does not depend on the compiler version.

jro

**Comment by sayerhs** [comment]
@overfelt Yeah, handling regression tests on different machines is a bit of a pain. Here is what I do. Nalu-Wind provides a custom `NALU_GOLD_NORMS_DIR` that you can use to point to your own set of Gold files. So I check out a working version of the `master` branch run regression tests copy `norm` files from that specific machine/compiler to a directory and then run CMake again to point to that directory for use with the development/feature branches. This is not ideal, but is useful to determine if the diffs are just order of operations or if there is something bigger that needs to be addressed.
