### ISSUE TITLE
ramping up inlet boundary conditions

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#640]
Hi Nalu-wind team,

I am wondering if there is a feature in Nalu-wind where we can provide time-dependent boundary condition in the inlet. This typically helps in doing ramp up tests in the inlet condition. As of now, doing multiple restarts is a work-around, and wondering if there is already an existing way to add time-dependancy to boundary conditions. 

Best Regards,

**Comment by sayerhs** [comment]
@tchatte3 You have two options for this:

- If you can parametrize your time-dependent BC in some analytical form, you can write up a user function and set that in the input file
- You can use the `time_varying_inflow` pre-processing utility and use transfers similar to ABL precursor (https://github.com/Exawind/wind-utils/blob/master/src/preprocessing/InflowHistory.cpp#L34). The user function pathway is better because it will be more efficient than transfers.

**Comment by tchatte3** [comment]
@sayerhs Thank you for the detailed output. If I use transfers, there will be 2 steps involved, user function seems to be a better option by registering the inflow BC. A follow up question, what is the variable used for ``time" in this regard?

Best Regards,

**Comment by sayerhs** [comment]
@tchatte3 The time argument is passed to the evaluation method in the user function. It is the second argument to the method, and ignored in cases like shear profile. See this time-varying convecting taylor vortex example for its usage.

https://github.com/Exawind/nalu-wind/blob/792e5368690551cd1a5f7cd7797606118f3a7e24/src/user_functions/ConvectingTaylorVortexVelocityAuxFunction.C#L35-L58

**Comment by tchatte3** [comment]
@sayerhs , Thank you  WindEnergyTaylorVortexAuxFunction.C is a good starting point. Sorry, I did not see you mention that in the first post. I really appreciate your help regarding this matter.
