### ISSUE TITLE
Issues from #725

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#740]
I'm seeing many segfaults in the tests after #725. I can't really tell if it's just a mesh issue or something with the code. The clang tests will give backtraces if that helps.

**Comment by sayerhs** [comment]
@psakievich The refactor of Peclet blending seems to introduce diffs in tests. Did you observe this when you did your runs? What is the expected magnitude for the diffs before we rebless the tests?

**Comment by psakievich** [comment]
@sayerhs I didn't observe noticeable diffs but the tolerances weren't super tight. I'll take a closer look at this today with gcc.  Working on fixing the unit test right now that is failing in parallel.

**Comment by psakievich** [comment]
Seems like there are two classes of diffs: ablUnstable and interface problems (overset and dg).

So running these locally I'm seeing the ablUnstable tests failing at the commit before #725.  I have not done a formal bisect yet to see exactly where they break but the norms are going crazy indicating divergence which makes me think this is not due to #725, but something earlier.  Might be good to confirm on another machine though. I've been testing with GCC 7.2 on a ceerws machine.

The dg and nonconformal ones are passing on the commit before #725. I've manually checked the norms to ensure they are the exact same as the golds.  I'm not very familiar with these parts of the code.  Maybe there is a copy or something that is sensitive to moving the Peclet factor to a field? I looked around a bit today, but nothing stood out to me. Thoughts @sayerhs?  I placed the Peclet computation right before the assemble call in the overset iteration loop so it _should_ be the same as the inline case, but for these interface problems it obviously is not.

**Comment by sayerhs** [comment]
@psakievich 

- The diffs for overset/DG with moving mesh seem straightforward and the latest re-bless (16990b9) has fixed it – [CDash](https://my.cdash.org/viewTest.php?onlypassed&buildid=1913737). 

- `ablUnstableEdge` is fine on gcc/linux builds but is failing on non-gcc/linux builds - this is related to #698 and follow-up commits that attempted to fix warnings, etc. This particular one is a restart where we are switching _planar averaging_ to _local averaging_ when computing the wall stress terms. This one is unrelated to #725, I am working with @mchurchf to get to the bottom of this. Right now, I think this might just be a matter of some bad parameter in the input file. 

The [failures on GPU](https://my.cdash.org/test/14517493) are something which we don't have a good handle on. Initially, @jrood-nrel  suspected that this was because he had recently started enabling hypre on GPU builds. However, ActLineSimpleNGP test indicates it happens even when we are not using the hypre solver path. @PaulMullowney did a bisect and it pointed to #725, but I am not sure why the particular code would cause a CUDA memory error. We do *use a lot of fields on device*, so one guess is that we are exhausting memory on GPUs... but I've not verified this.

**Comment by alanw0** [comment]
In case it helps, we have a stk function in stk_util/environment/memory_util.hpp, 'void get_gpu_memory_info(size_t& used, size_t& free);'
That could show how close we are getting to the memory limit of the device.

**Comment by psakievich** [comment]
@sayerhs thanks for the update. I'm going to unassign myself from this issue since it appears you guys have already worked out most of the details, and I don't want to keep replicating results that have already been obtained. Please let me know if I you'd like my help with the GPU issues.
