### ISSUE TITLE
Remove Examples ABL/ALM

### ISSUE THREAD

**Issue by tonyinme** [Exawind/nalu-wind#836]
@sayerhs and I were thinking of removing the [examples](https://github.com/Exawind/nalu-wind/tree/master/examples) for ABL/ALM from the repository.

As we start transitioning the ABL/ALM/ADM simulation workflow to amr-wind, these examples have stopped being useful and create confusion among users. We are also not updating them anymore and they have become deprecated. 

The regression tests will still be in the repository and can be used as examples.

Let us know if you agree with removing the examples.

**Comment by jrood-nrel** [comment]
I looked through these recently and I agree. They have gotten quite out of date and they should probably be removed.

**Comment by lawrenceccheung** [comment]
Should we wait until we have the equivalent examples in amr-wind, and then remove them here?

Lawrence

**Comment by psakievich** [comment]
I agree with removing these, but I think there are some things we should add to the regression test suite in their absence.  At a minimum I think we need a multi-turbine ALM and/or ADM test, and it would be good to have one that also uses inflow/outflow from a stored precursor.  The precursor probably only needs to have two timesteps that can be interpolated over. This could also be a good candidate for a new performance test. 

I think as long as we maintain actuator capability in Nalu-Wind we need to have some example of how these simulations are setup and run readily available to the user base since they are core wind energy applications.

**Comment by sayerhs** [comment]
@psakievich Regarding _inflow/outflow from a stored precursor_, please see [ablUnstableEdge_rst](https://github.com/Exawind/nalu-wind/blob/master/reg_tests/test_files/ablUnstableEdge/ablUnstableEdge_rst.yaml)

**Comment by sayerhs** [comment]
@lawrenceccheung These examples are not part of any automated test workflow and, therefore, are often outdated. For example, if you try to run any of the actuator example files now they will fail. The proper solution here is to convert them to regression tests so that it gets run everyday. The tutorials should refer to the files in the regression test and not something that would suffer from code rot.

**Comment by psakievich** [comment]
@sayerhs I'm aware of that regression test.  To clarify, I believe adding a multi-turbine test is the necessary addition. We probably should have had one all along.  A representative test that exercises multiple turbines with inflow-outflow would be nice as a performance test to represent a core wind energy application, but not necessary from a strict test coverage stand point.  We could add more bells and whistles to the performance test as well. Maybe complex terrain or something.

**Comment by psakievich** [comment]
I 100% agree with @sayerhs about the lack of usefulness due to being outside the standard testing paradigm.  If they aren't being run on a semi regular basis then they are sure to get out of date and in the rush of the development cycle we forget to circle back and update them.  We should make sure that any example we have in AMR-Wind is also run regularly, and the most straight forward way to do that is to make it a regression test, or a performance test that gets run regularly albeit less frequently due to increased complexity and size.

**Comment by lawrenceccheung** [comment]
Expanding on @psakievich's point a bit, maybe we can somehow link the example cases to the regression test, except increase the simulation time or add additional outputs (we can also do the reverse, link the regression test to the example case).  That way they'd always be up to date.

Lawrence

**Comment by tonyinme** [comment]
Hey all, it looks like this issue will be resolved with #837 

@psakievich and @lawrenceccheung, I will leave this open for now but feel free to remove the examples and close this whenever you are ready.

**Comment by brandonneth** [comment]
Hi yall, I was working on getting the examples running and found this when I ran into some issues. Do you have a recommendation for which regression test to start with instead of the wind farm examples? Thanks!

**Comment by psakievich** [comment]
@lawrenceccheung do you have an example you can share with @brandonneth?

**Comment by lawrenceccheung** [comment]
Yeah, the example cases are a bit out of date.  For the ABL case, I would start with
https://github.com/Exawind/nalu-wind/blob/master/reg_tests/test_files/ablNeutralEdge/ablNeutralEdge.yaml
or possibly this case
https://github.com/Exawind/wind-energy/blob/master/Pedersen_N02/NaluWindRun02/nalu_neutral_v3.yaml,

and for the actuator line turbine case I would take a look at
https://github.com/Exawind/nalu-wind/tree/master/reg_tests/test_files/nrel5MWactuatorLine

Lawrence
