### ISSUE TITLE
Segfaults in CPU builds

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#886]
Starting this issue to track resolution of CPU segfaults observed on the dashboard.  One example is the unit tests here:  https://my.cdash.org/test/40678792

**Comment by tasmith4** [comment]
FYI @jrood-nrel.

I can reproduce and it seems to be coming from some STK field usage, although it's not totally obvious what's going on yet.  We'll follow up with this on the STK side.

**Comment by jrood-nrel** [comment]
https://my.cdash.org/test/40683694 shows a pretty clear stack trace

**Comment by alanw0** [comment]
Ugh. I'm pretty sure I know what's going on. It's the change we made to allocate views of FieldInfo thingy's without initializing. That's the right thing to do for the device view in a GPU build, but when we're on a CPU build the view is never getting initialized (the objects are not getting constructed) because the deep_copy is a no-op. We'll get this straightened out asap.
